package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AcGrants.
 */
public class AcGrants {

    private Long id;
    private String UserCode;
    private String AcReg;
    private String AcType;
    private Float AcRegBw;
    private Float AcLj;
    private String IsCaption;
    private int SysVersion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AcGrants() {
    }

    public AcGrants(Long id) {
        this.id = id;
    }

    public AcGrants(Long id, String UserCode, String AcReg, String AcType, Float AcRegBw, Float AcLj, String IsCaption, int SysVersion) {
        this.id = id;
        this.UserCode = UserCode;
        this.AcReg = AcReg;
        this.AcType = AcType;
        this.AcRegBw = AcRegBw;
        this.AcLj = AcLj;
        this.IsCaption = IsCaption;
        this.SysVersion = SysVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public String getAcReg() {
        return AcReg;
    }

    public void setAcReg(String AcReg) {
        this.AcReg = AcReg;
    }

    public String getAcType() {
        return AcType;
    }

    public void setAcType(String AcType) {
        this.AcType = AcType;
    }

    public Float getAcRegBw() {
        return AcRegBw;
    }

    public void setAcRegBw(Float AcRegBw) {
        this.AcRegBw = AcRegBw;
    }

    public Float getAcLj() {
        return AcLj;
    }

    public void setAcLj(Float AcLj) {
        this.AcLj = AcLj;
    }

    public String getIsCaption() {
        return IsCaption;
    }

    public void setIsCaption(String IsCaption) {
        this.IsCaption = IsCaption;
    }

    public int getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(int SysVersion) {
        this.SysVersion = SysVersion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
