package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ACTION_FEED.
 */
public class ActionFeed {

    private Long id;
    private Integer feed_type;
    private String feed_id;
    private String UserCode;
    private String FlightId;
    private Integer feed_status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ActionFeed() {
    }

    public ActionFeed(Long id) {
        this.id = id;
    }

    public ActionFeed(Long id, Integer feed_type, String feed_id, String UserCode, String FlightId, Integer feed_status) {
        this.id = id;
        this.feed_type = feed_type;
        this.feed_id = feed_id;
        this.UserCode = UserCode;
        this.FlightId = FlightId;
        this.feed_status = feed_status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getFeed_type() {
        return feed_type;
    }

    public void setFeed_type(Integer feed_type) {
        this.feed_type = feed_type;
    }

    public String getFeed_id() {
        return feed_id;
    }

    public void setFeed_id(String feed_id) {
        this.feed_id = feed_id;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public String getFlightId() {
        return FlightId;
    }

    public void setFlightId(String FlightId) {
        this.FlightId = FlightId;
    }

    public Integer getFeed_status() {
        return feed_status;
    }

    public void setFeed_status(Integer feed_status) {
        this.feed_status = feed_status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
