package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AC_WEIGHT_LIMIT.
 */
public class AcWeightLimit {

    private Long id;
    private String AcType;
    private Float Weight;
    private Float WeightCg1;
    private Float WeightCg2;
    private String OpUser;
    private int SysVersion;
    private String OpDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AcWeightLimit() {
    }

    public AcWeightLimit(Long id) {
        this.id = id;
    }

    public AcWeightLimit(Long id, String AcType, Float Weight, Float WeightCg1, Float WeightCg2, String OpUser, int SysVersion, String OpDate) {
        this.id = id;
        this.AcType = AcType;
        this.Weight = Weight;
        this.WeightCg1 = WeightCg1;
        this.WeightCg2 = WeightCg2;
        this.OpUser = OpUser;
        this.SysVersion = SysVersion;
        this.OpDate = OpDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAcType() {
        return AcType;
    }

    public void setAcType(String AcType) {
        this.AcType = AcType;
    }

    public Float getWeight() {
        return Weight;
    }

    public void setWeight(Float Weight) {
        this.Weight = Weight;
    }

    public Float getWeightCg1() {
        return WeightCg1;
    }

    public void setWeightCg1(Float WeightCg1) {
        this.WeightCg1 = WeightCg1;
    }

    public Float getWeightCg2() {
        return WeightCg2;
    }

    public void setWeightCg2(Float WeightCg2) {
        this.WeightCg2 = WeightCg2;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public int getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(int SysVersion) {
        this.SysVersion = SysVersion;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
