package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
// KEEP INCLUDES END
/**
 * Entity mapped to table ADD_FLIGHT_INFO.
 */
public class AddFlightInfo {

    private Long id;
    private String FlightDate;
    /** Not-null value. */
    private String FlightId;
    private String AircraftReg;
    private String AircraftType;
    private String FlightNo;
    private String Dep4Code;
    private String DepAirportName;
    private String Arr4Code;
    private String ArrAirportName;
    private String MaxFule;
    private String RealFule;
    private String SlieFule;
    private String RouteFule;
    private String TofWeight;
    private String LandWeight;
    private String NoFuleWeight;
    private String AirportLimitWeight;
    private String BalancePic;
    private String BalancePicName;
    private String OpUser;
    private String OpDate;
    private String weightCg;
    private String Caption;
    private String TkoZx;
    private String TkoMac;
    private String passengerWeight;
    private String articleWeight;
    private String beforeFlyFule;
    private String landWeightCg;
    private String beforeWCgmin;
    private String beforeWCgmax;
    private String landWCgmin;
    private String landWCgmax;
    private Float UseWeight;
    private Float UseWeightCg;
    private String BasicWeight;
    private Float allSbLj;

    // KEEP FIELDS - put your custom fields here
    private ArrayList<Integer> sbList;
    // KEEP FIELDS END

    public AddFlightInfo() {
    }

    public AddFlightInfo(Long id) {
        this.id = id;
    }

    public AddFlightInfo(Long id, String FlightDate, String FlightId, String AircraftReg, String AircraftType, String FlightNo, String Dep4Code, String DepAirportName, String Arr4Code, String ArrAirportName, String MaxFule, String RealFule, String SlieFule, String RouteFule, String TofWeight, String LandWeight, String NoFuleWeight, String AirportLimitWeight, String BalancePic, String BalancePicName, String OpUser, String OpDate, String weightCg, String Caption, String TkoZx, String TkoMac, String passengerWeight, String articleWeight, String beforeFlyFule, String landWeightCg, String beforeWCgmin, String beforeWCgmax, String landWCgmin, String landWCgmax, Float UseWeight, Float UseWeightCg, String BasicWeight, Float allSbLj) {
        this.id = id;
        this.FlightDate = FlightDate;
        this.FlightId = FlightId;
        this.AircraftReg = AircraftReg;
        this.AircraftType = AircraftType;
        this.FlightNo = FlightNo;
        this.Dep4Code = Dep4Code;
        this.DepAirportName = DepAirportName;
        this.Arr4Code = Arr4Code;
        this.ArrAirportName = ArrAirportName;
        this.MaxFule = MaxFule;
        this.RealFule = RealFule;
        this.SlieFule = SlieFule;
        this.RouteFule = RouteFule;
        this.TofWeight = TofWeight;
        this.LandWeight = LandWeight;
        this.NoFuleWeight = NoFuleWeight;
        this.AirportLimitWeight = AirportLimitWeight;
        this.BalancePic = BalancePic;
        this.BalancePicName = BalancePicName;
        this.OpUser = OpUser;
        this.OpDate = OpDate;
        this.weightCg = weightCg;
        this.Caption = Caption;
        this.TkoZx = TkoZx;
        this.TkoMac = TkoMac;
        this.passengerWeight = passengerWeight;
        this.articleWeight = articleWeight;
        this.beforeFlyFule = beforeFlyFule;
        this.landWeightCg = landWeightCg;
        this.beforeWCgmin = beforeWCgmin;
        this.beforeWCgmax = beforeWCgmax;
        this.landWCgmin = landWCgmin;
        this.landWCgmax = landWCgmax;
        this.UseWeight = UseWeight;
        this.UseWeightCg = UseWeightCg;
        this.BasicWeight = BasicWeight;
        this.allSbLj = allSbLj;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFlightDate() {
        return FlightDate;
    }

    public void setFlightDate(String FlightDate) {
        this.FlightDate = FlightDate;
    }

    /** Not-null value. */
    public String getFlightId() {
        return FlightId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFlightId(String FlightId) {
        this.FlightId = FlightId;
    }

    public String getAircraftReg() {
        return AircraftReg;
    }

    public void setAircraftReg(String AircraftReg) {
        this.AircraftReg = AircraftReg;
    }

    public String getAircraftType() {
        return AircraftType;
    }

    public void setAircraftType(String AircraftType) {
        this.AircraftType = AircraftType;
    }

    public String getFlightNo() {
        return FlightNo;
    }

    public void setFlightNo(String FlightNo) {
        this.FlightNo = FlightNo;
    }

    public String getDep4Code() {
        return Dep4Code;
    }

    public void setDep4Code(String Dep4Code) {
        this.Dep4Code = Dep4Code;
    }

    public String getDepAirportName() {
        return DepAirportName;
    }

    public void setDepAirportName(String DepAirportName) {
        this.DepAirportName = DepAirportName;
    }

    public String getArr4Code() {
        return Arr4Code;
    }

    public void setArr4Code(String Arr4Code) {
        this.Arr4Code = Arr4Code;
    }

    public String getArrAirportName() {
        return ArrAirportName;
    }

    public void setArrAirportName(String ArrAirportName) {
        this.ArrAirportName = ArrAirportName;
    }

    public String getMaxFule() {
        return MaxFule;
    }

    public void setMaxFule(String MaxFule) {
        this.MaxFule = MaxFule;
    }

    public String getRealFule() {
        return RealFule;
    }

    public void setRealFule(String RealFule) {
        this.RealFule = RealFule;
    }

    public String getSlieFule() {
        return SlieFule;
    }

    public void setSlieFule(String SlieFule) {
        this.SlieFule = SlieFule;
    }

    public String getRouteFule() {
        return RouteFule;
    }

    public void setRouteFule(String RouteFule) {
        this.RouteFule = RouteFule;
    }

    public String getTofWeight() {
        return TofWeight;
    }

    public void setTofWeight(String TofWeight) {
        this.TofWeight = TofWeight;
    }

    public String getLandWeight() {
        return LandWeight;
    }

    public void setLandWeight(String LandWeight) {
        this.LandWeight = LandWeight;
    }

    public String getNoFuleWeight() {
        return NoFuleWeight;
    }

    public void setNoFuleWeight(String NoFuleWeight) {
        this.NoFuleWeight = NoFuleWeight;
    }

    public String getAirportLimitWeight() {
        return AirportLimitWeight;
    }

    public void setAirportLimitWeight(String AirportLimitWeight) {
        this.AirportLimitWeight = AirportLimitWeight;
    }

    public String getBalancePic() {
        return BalancePic;
    }

    public void setBalancePic(String BalancePic) {
        this.BalancePic = BalancePic;
    }

    public String getBalancePicName() {
        return BalancePicName;
    }

    public void setBalancePicName(String BalancePicName) {
        this.BalancePicName = BalancePicName;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    public String getWeightCg() {
        return weightCg;
    }

    public void setWeightCg(String weightCg) {
        this.weightCg = weightCg;
    }

    public String getCaption() {
        return Caption;
    }

    public void setCaption(String Caption) {
        this.Caption = Caption;
    }

    public String getTkoZx() {
        return TkoZx;
    }

    public void setTkoZx(String TkoZx) {
        this.TkoZx = TkoZx;
    }

    public String getTkoMac() {
        return TkoMac;
    }

    public void setTkoMac(String TkoMac) {
        this.TkoMac = TkoMac;
    }

    public String getPassengerWeight() {
        return passengerWeight;
    }

    public void setPassengerWeight(String passengerWeight) {
        this.passengerWeight = passengerWeight;
    }

    public String getArticleWeight() {
        return articleWeight;
    }

    public void setArticleWeight(String articleWeight) {
        this.articleWeight = articleWeight;
    }

    public String getBeforeFlyFule() {
        return beforeFlyFule;
    }

    public void setBeforeFlyFule(String beforeFlyFule) {
        this.beforeFlyFule = beforeFlyFule;
    }

    public String getLandWeightCg() {
        return landWeightCg;
    }

    public void setLandWeightCg(String landWeightCg) {
        this.landWeightCg = landWeightCg;
    }

    public String getBeforeWCgmin() {
        return beforeWCgmin;
    }

    public void setBeforeWCgmin(String beforeWCgmin) {
        this.beforeWCgmin = beforeWCgmin;
    }

    public String getBeforeWCgmax() {
        return beforeWCgmax;
    }

    public void setBeforeWCgmax(String beforeWCgmax) {
        this.beforeWCgmax = beforeWCgmax;
    }

    public String getLandWCgmin() {
        return landWCgmin;
    }

    public void setLandWCgmin(String landWCgmin) {
        this.landWCgmin = landWCgmin;
    }

    public String getLandWCgmax() {
        return landWCgmax;
    }

    public void setLandWCgmax(String landWCgmax) {
        this.landWCgmax = landWCgmax;
    }

    public Float getUseWeight() {
        return UseWeight;
    }

    public void setUseWeight(Float UseWeight) {
        this.UseWeight = UseWeight;
    }

    public Float getUseWeightCg() {
        return UseWeightCg;
    }

    public void setUseWeightCg(Float UseWeightCg) {
        this.UseWeightCg = UseWeightCg;
    }

    public String getBasicWeight() {
        return BasicWeight;
    }

    public void setBasicWeight(String BasicWeight) {
        this.BasicWeight = BasicWeight;
    }

    public Float getAllSbLj() {
        return allSbLj;
    }

    public void setAllSbLj(Float allSbLj) {
        this.allSbLj = allSbLj;
    }

    // KEEP METHODS - put your custom methods here
    public void setSbList(ArrayList<Integer> sbList) {
        this.sbList = sbList;
    }

    public ArrayList<Integer> getSbList() {
        return sbList;
    }
    // KEEP METHODS END

}
