package com.xiaoqing.flight.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xiaoqing.flight.data.dao.AddFlightInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ADD_FLIGHT_INFO.
*/
public class AddFlightInfoDao extends AbstractDao<AddFlightInfo, String> {

    public static final String TABLENAME = "ADD_FLIGHT_INFO";

    /**
     * Properties of entity AddFlightInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FlightId = new Property(0, String.class, "FlightId", true, "FLIGHT_ID");
        public final static Property FlightDate = new Property(1, String.class, "FlightDate", false, "FLIGHT_DATE");
        public final static Property AircraftReg = new Property(2, String.class, "AircraftReg", false, "AIRCRAFT_REG");
        public final static Property AircraftType = new Property(3, String.class, "AircraftType", false, "AIRCRAFT_TYPE");
        public final static Property FlightNo = new Property(4, String.class, "FlightNo", false, "FLIGHT_NO");
        public final static Property Dep4Code = new Property(5, String.class, "Dep4Code", false, "DEP4_CODE");
        public final static Property DepAirportName = new Property(6, String.class, "DepAirportName", false, "DEP_AIRPORT_NAME");
        public final static Property Arr4Code = new Property(7, String.class, "Arr4Code", false, "ARR4_CODE");
        public final static Property ArrAirportName = new Property(8, String.class, "ArrAirportName", false, "ARR_AIRPORT_NAME");
        public final static Property MaxFule = new Property(9, String.class, "MaxFule", false, "MAX_FULE");
        public final static Property RealFule = new Property(10, String.class, "RealFule", false, "REAL_FULE");
        public final static Property SlieFule = new Property(11, String.class, "SlieFule", false, "SLIE_FULE");
        public final static Property RouteFule = new Property(12, String.class, "RouteFule", false, "ROUTE_FULE");
        public final static Property TofWeight = new Property(13, String.class, "TofWeight", false, "TOF_WEIGHT");
        public final static Property LandWeight = new Property(14, String.class, "LandWeight", false, "LAND_WEIGHT");
        public final static Property NoFuleWeight = new Property(15, String.class, "NoFuleWeight", false, "NO_FULE_WEIGHT");
        public final static Property AirportLimitWeight = new Property(16, String.class, "AirportLimitWeight", false, "AIRPORT_LIMIT_WEIGHT");
        public final static Property BalancePic = new Property(17, String.class, "BalancePic", false, "BALANCE_PIC");
        public final static Property BalancePicName = new Property(18, String.class, "BalancePicName", false, "BALANCE_PIC_NAME");
        public final static Property OpUser = new Property(19, String.class, "OpUser", false, "OP_USER");
        public final static Property OpDate = new Property(20, String.class, "OpDate", false, "OP_DATE");
        public final static Property WeightCg = new Property(21, String.class, "weightCg", false, "WEIGHT_CG");
        public final static Property Caption = new Property(22, String.class, "Caption", false, "CAPTION");
        public final static Property TkoZx = new Property(23, String.class, "TkoZx", false, "TKO_ZX");
        public final static Property TkoMac = new Property(24, String.class, "TkoMac", false, "TKO_MAC");
    };


    public AddFlightInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AddFlightInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ADD_FLIGHT_INFO' (" + //
                "'FLIGHT_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: FlightId
                "'FLIGHT_DATE' TEXT," + // 1: FlightDate
                "'AIRCRAFT_REG' TEXT," + // 2: AircraftReg
                "'AIRCRAFT_TYPE' TEXT," + // 3: AircraftType
                "'FLIGHT_NO' TEXT," + // 4: FlightNo
                "'DEP4_CODE' TEXT," + // 5: Dep4Code
                "'DEP_AIRPORT_NAME' TEXT," + // 6: DepAirportName
                "'ARR4_CODE' TEXT," + // 7: Arr4Code
                "'ARR_AIRPORT_NAME' TEXT," + // 8: ArrAirportName
                "'MAX_FULE' TEXT," + // 9: MaxFule
                "'REAL_FULE' TEXT," + // 10: RealFule
                "'SLIE_FULE' TEXT," + // 11: SlieFule
                "'ROUTE_FULE' TEXT," + // 12: RouteFule
                "'TOF_WEIGHT' TEXT," + // 13: TofWeight
                "'LAND_WEIGHT' TEXT," + // 14: LandWeight
                "'NO_FULE_WEIGHT' TEXT," + // 15: NoFuleWeight
                "'AIRPORT_LIMIT_WEIGHT' TEXT," + // 16: AirportLimitWeight
                "'BALANCE_PIC' TEXT," + // 17: BalancePic
                "'BALANCE_PIC_NAME' TEXT," + // 18: BalancePicName
                "'OP_USER' TEXT," + // 19: OpUser
                "'OP_DATE' TEXT," + // 20: OpDate
                "'WEIGHT_CG' TEXT," + // 21: weightCg
                "'CAPTION' TEXT," + // 22: Caption
                "'TKO_ZX' TEXT," + // 23: TkoZx
                "'TKO_MAC' TEXT);"); // 24: TkoMac
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ADD_FLIGHT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AddFlightInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFlightId());
 
        String FlightDate = entity.getFlightDate();
        if (FlightDate != null) {
            stmt.bindString(2, FlightDate);
        }
 
        String AircraftReg = entity.getAircraftReg();
        if (AircraftReg != null) {
            stmt.bindString(3, AircraftReg);
        }
 
        String AircraftType = entity.getAircraftType();
        if (AircraftType != null) {
            stmt.bindString(4, AircraftType);
        }
 
        String FlightNo = entity.getFlightNo();
        if (FlightNo != null) {
            stmt.bindString(5, FlightNo);
        }
 
        String Dep4Code = entity.getDep4Code();
        if (Dep4Code != null) {
            stmt.bindString(6, Dep4Code);
        }
 
        String DepAirportName = entity.getDepAirportName();
        if (DepAirportName != null) {
            stmt.bindString(7, DepAirportName);
        }
 
        String Arr4Code = entity.getArr4Code();
        if (Arr4Code != null) {
            stmt.bindString(8, Arr4Code);
        }
 
        String ArrAirportName = entity.getArrAirportName();
        if (ArrAirportName != null) {
            stmt.bindString(9, ArrAirportName);
        }
 
        String MaxFule = entity.getMaxFule();
        if (MaxFule != null) {
            stmt.bindString(10, MaxFule);
        }
 
        String RealFule = entity.getRealFule();
        if (RealFule != null) {
            stmt.bindString(11, RealFule);
        }
 
        String SlieFule = entity.getSlieFule();
        if (SlieFule != null) {
            stmt.bindString(12, SlieFule);
        }
 
        String RouteFule = entity.getRouteFule();
        if (RouteFule != null) {
            stmt.bindString(13, RouteFule);
        }
 
        String TofWeight = entity.getTofWeight();
        if (TofWeight != null) {
            stmt.bindString(14, TofWeight);
        }
 
        String LandWeight = entity.getLandWeight();
        if (LandWeight != null) {
            stmt.bindString(15, LandWeight);
        }
 
        String NoFuleWeight = entity.getNoFuleWeight();
        if (NoFuleWeight != null) {
            stmt.bindString(16, NoFuleWeight);
        }
 
        String AirportLimitWeight = entity.getAirportLimitWeight();
        if (AirportLimitWeight != null) {
            stmt.bindString(17, AirportLimitWeight);
        }
 
        String BalancePic = entity.getBalancePic();
        if (BalancePic != null) {
            stmt.bindString(18, BalancePic);
        }
 
        String BalancePicName = entity.getBalancePicName();
        if (BalancePicName != null) {
            stmt.bindString(19, BalancePicName);
        }
 
        String OpUser = entity.getOpUser();
        if (OpUser != null) {
            stmt.bindString(20, OpUser);
        }
 
        String OpDate = entity.getOpDate();
        if (OpDate != null) {
            stmt.bindString(21, OpDate);
        }
 
        String weightCg = entity.getWeightCg();
        if (weightCg != null) {
            stmt.bindString(22, weightCg);
        }
 
        String Caption = entity.getCaption();
        if (Caption != null) {
            stmt.bindString(23, Caption);
        }
 
        String TkoZx = entity.getTkoZx();
        if (TkoZx != null) {
            stmt.bindString(24, TkoZx);
        }
 
        String TkoMac = entity.getTkoMac();
        if (TkoMac != null) {
            stmt.bindString(25, TkoMac);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AddFlightInfo readEntity(Cursor cursor, int offset) {
        AddFlightInfo entity = new AddFlightInfo( //
            cursor.getString(offset + 0), // FlightId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // FlightDate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // AircraftReg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // AircraftType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // FlightNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Dep4Code
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // DepAirportName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Arr4Code
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ArrAirportName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // MaxFule
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // RealFule
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // SlieFule
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // RouteFule
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // TofWeight
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // LandWeight
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // NoFuleWeight
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // AirportLimitWeight
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // BalancePic
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // BalancePicName
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // OpUser
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // OpDate
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // weightCg
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // Caption
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // TkoZx
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24) // TkoMac
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AddFlightInfo entity, int offset) {
        entity.setFlightId(cursor.getString(offset + 0));
        entity.setFlightDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAircraftReg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAircraftType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFlightNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDep4Code(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDepAirportName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setArr4Code(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setArrAirportName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMaxFule(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRealFule(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSlieFule(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRouteFule(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTofWeight(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setLandWeight(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setNoFuleWeight(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setAirportLimitWeight(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setBalancePic(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setBalancePicName(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setOpUser(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setOpDate(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setWeightCg(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setCaption(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTkoZx(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTkoMac(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(AddFlightInfo entity, long rowId) {
        return entity.getFlightId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(AddFlightInfo entity) {
        if(entity != null) {
            return entity.getFlightId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
