package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALL_AIRPORT.
 */
public class AllAirport {

    private Long id;
    private String Str4code;
    private String StrAirportName;
    private int SysVersion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AllAirport() {
    }

    public AllAirport(Long id) {
        this.id = id;
    }

    public AllAirport(Long id, String Str4code, String StrAirportName, int SysVersion) {
        this.id = id;
        this.Str4code = Str4code;
        this.StrAirportName = StrAirportName;
        this.SysVersion = SysVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStr4code() {
        return Str4code;
    }

    public void setStr4code(String Str4code) {
        this.Str4code = Str4code;
    }

    public String getStrAirportName() {
        return StrAirportName;
    }

    public void setStrAirportName(String StrAirportName) {
        this.StrAirportName = StrAirportName;
    }

    public int getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(int SysVersion) {
        this.SysVersion = SysVersion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
