package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALL_AC_TYPE.
 */
public class AllAcType {

    private Long id;
    /** Not-null value. */
    private String AircraftType;
    private float PortLimit;
    private String LimitType;
    private String AircraftTypeChName;
    private float TofWeightLimit;
    private float LandWeightLimit;
    private float Mzfw;
    private String Mac;
    private String Mac2;
    private String OpDate;
    private int SysVersion;
    private String UserCode;
    private String MacFlg;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AllAcType() {
    }

    public AllAcType(Long id) {
        this.id = id;
    }

    public AllAcType(Long id, String AircraftType, float PortLimit, String LimitType, String AircraftTypeChName, float TofWeightLimit, float LandWeightLimit, float Mzfw, String Mac, String Mac2, String OpDate, int SysVersion, String UserCode, String MacFlg) {
        this.id = id;
        this.AircraftType = AircraftType;
        this.PortLimit = PortLimit;
        this.LimitType = LimitType;
        this.AircraftTypeChName = AircraftTypeChName;
        this.TofWeightLimit = TofWeightLimit;
        this.LandWeightLimit = LandWeightLimit;
        this.Mzfw = Mzfw;
        this.Mac = Mac;
        this.Mac2 = Mac2;
        this.OpDate = OpDate;
        this.SysVersion = SysVersion;
        this.UserCode = UserCode;
        this.MacFlg = MacFlg;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAircraftType() {
        return AircraftType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAircraftType(String AircraftType) {
        this.AircraftType = AircraftType;
    }

    public float getPortLimit() {
        return PortLimit;
    }

    public void setPortLimit(float PortLimit) {
        this.PortLimit = PortLimit;
    }

    public String getLimitType() {
        return LimitType;
    }

    public void setLimitType(String LimitType) {
        this.LimitType = LimitType;
    }

    public String getAircraftTypeChName() {
        return AircraftTypeChName;
    }

    public void setAircraftTypeChName(String AircraftTypeChName) {
        this.AircraftTypeChName = AircraftTypeChName;
    }

    public float getTofWeightLimit() {
        return TofWeightLimit;
    }

    public void setTofWeightLimit(float TofWeightLimit) {
        this.TofWeightLimit = TofWeightLimit;
    }

    public float getLandWeightLimit() {
        return LandWeightLimit;
    }

    public void setLandWeightLimit(float LandWeightLimit) {
        this.LandWeightLimit = LandWeightLimit;
    }

    public float getMzfw() {
        return Mzfw;
    }

    public void setMzfw(float Mzfw) {
        this.Mzfw = Mzfw;
    }

    public String getMac() {
        return Mac;
    }

    public void setMac(String Mac) {
        this.Mac = Mac;
    }

    public String getMac2() {
        return Mac2;
    }

    public void setMac2(String Mac2) {
        this.Mac2 = Mac2;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    public int getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(int SysVersion) {
        this.SysVersion = SysVersion;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public String getMacFlg() {
        return MacFlg;
    }

    public void setMacFlg(String MacFlg) {
        this.MacFlg = MacFlg;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
