package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALL_AC_SB.
 */
public class AllAcSb {

    private Long id;
    private String AcReg;
    private Integer SbId;
    private Float SbWeight;
    private Float SbLb;
    private String OpUser;
    private String OpDate;
    private Integer Sysversion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AllAcSb() {
    }

    public AllAcSb(Long id) {
        this.id = id;
    }

    public AllAcSb(Long id, String AcReg, Integer SbId, Float SbWeight, Float SbLb, String OpUser, String OpDate, Integer Sysversion) {
        this.id = id;
        this.AcReg = AcReg;
        this.SbId = SbId;
        this.SbWeight = SbWeight;
        this.SbLb = SbLb;
        this.OpUser = OpUser;
        this.OpDate = OpDate;
        this.Sysversion = Sysversion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAcReg() {
        return AcReg;
    }

    public void setAcReg(String AcReg) {
        this.AcReg = AcReg;
    }

    public Integer getSbId() {
        return SbId;
    }

    public void setSbId(Integer SbId) {
        this.SbId = SbId;
    }

    public Float getSbWeight() {
        return SbWeight;
    }

    public void setSbWeight(Float SbWeight) {
        this.SbWeight = SbWeight;
    }

    public Float getSbLb() {
        return SbLb;
    }

    public void setSbLb(Float SbLb) {
        this.SbLb = SbLb;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    public Integer getSysversion() {
        return Sysversion;
    }

    public void setSysversion(Integer Sysversion) {
        this.Sysversion = Sysversion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
