package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALL_SB.
 */
public class AllSb {

    private Long id;
    private Integer SbId;
    private String SbName;
    private Double SbWeight;
    private String AcType;
    private Integer SeatId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AllSb() {
    }

    public AllSb(Long id) {
        this.id = id;
    }

    public AllSb(Long id, Integer SbId, String SbName, Double SbWeight, String AcType, Integer SeatId) {
        this.id = id;
        this.SbId = SbId;
        this.SbName = SbName;
        this.SbWeight = SbWeight;
        this.AcType = AcType;
        this.SeatId = SeatId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSbId() {
        return SbId;
    }

    public void setSbId(Integer SbId) {
        this.SbId = SbId;
    }

    public String getSbName() {
        return SbName;
    }

    public void setSbName(String SbName) {
        this.SbName = SbName;
    }

    public Double getSbWeight() {
        return SbWeight;
    }

    public void setSbWeight(Double SbWeight) {
        this.SbWeight = SbWeight;
    }

    public String getAcType() {
        return AcType;
    }

    public void setAcType(String AcType) {
        this.AcType = AcType;
    }

    public Integer getSeatId() {
        return SeatId;
    }

    public void setSeatId(Integer SeatId) {
        this.SeatId = SeatId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
