package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PASSENGER.
 */
public class Passenger {

    private Long id;
    private String userName;
    private Double userWeight;
    private String AircraftReg;
    private Boolean isChecked;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Passenger() {
    }

    public Passenger(Long id) {
        this.id = id;
    }

    public Passenger(Long id, String userName, Double userWeight, String AircraftReg, Boolean isChecked) {
        this.id = id;
        this.userName = userName;
        this.userWeight = userWeight;
        this.AircraftReg = AircraftReg;
        this.isChecked = isChecked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Double getUserWeight() {
        return userWeight;
    }

    public void setUserWeight(Double userWeight) {
        this.userWeight = userWeight;
    }

    public String getAircraftReg() {
        return AircraftReg;
    }

    public void setAircraftReg(String AircraftReg) {
        this.AircraftReg = AircraftReg;
    }

    public Boolean getIsChecked() {
        return isChecked;
    }

    public void setIsChecked(Boolean isChecked) {
        this.isChecked = isChecked;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
