package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SEAT_BY_AC_REG.
 */
public class SeatByAcReg implements java.io.Serializable {

    private Long id;
    private String AcReg;
    private Integer SeatId;
    private String SeatCode;
    private String SeatType;
    private Float AcTypeSeatLimit;
    private Float AcTypeLb;
    private Float AcRegCargWeight;
    private Float AcRegSbWeight;
    private Float SeatLastLimit;
    private String OpUser;
    private String OpDate;
    private String SysVersion;
    private Float XPos;
    private Float YPos;
    private String Direction;
    private String userName;
    private float seatWeight;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SeatByAcReg() {
    }

    public SeatByAcReg(Long id) {
        this.id = id;
    }

    public SeatByAcReg(Long id, String AcReg, Integer SeatId, String SeatCode, String SeatType, Float AcTypeSeatLimit, Float AcTypeLb, Float AcRegCargWeight, Float AcRegSbWeight, Float SeatLastLimit, String OpUser, String OpDate, String SysVersion, Float XPos, Float YPos, String Direction, String userName, float seatWeight) {
        this.id = id;
        this.AcReg = AcReg;
        this.SeatId = SeatId;
        this.SeatCode = SeatCode;
        this.SeatType = SeatType;
        this.AcTypeSeatLimit = AcTypeSeatLimit;
        this.AcTypeLb = AcTypeLb;
        this.AcRegCargWeight = AcRegCargWeight;
        this.AcRegSbWeight = AcRegSbWeight;
        this.SeatLastLimit = SeatLastLimit;
        this.OpUser = OpUser;
        this.OpDate = OpDate;
        this.SysVersion = SysVersion;
        this.XPos = XPos;
        this.YPos = YPos;
        this.Direction = Direction;
        this.userName = userName;
        this.seatWeight = seatWeight;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAcReg() {
        return AcReg;
    }

    public void setAcReg(String AcReg) {
        this.AcReg = AcReg;
    }

    public Integer getSeatId() {
        return SeatId;
    }

    public void setSeatId(Integer SeatId) {
        this.SeatId = SeatId;
    }

    public String getSeatCode() {
        return SeatCode;
    }

    public void setSeatCode(String SeatCode) {
        this.SeatCode = SeatCode;
    }

    public String getSeatType() {
        return SeatType;
    }

    public void setSeatType(String SeatType) {
        this.SeatType = SeatType;
    }

    public Float getAcTypeSeatLimit() {
        return AcTypeSeatLimit;
    }

    public void setAcTypeSeatLimit(Float AcTypeSeatLimit) {
        this.AcTypeSeatLimit = AcTypeSeatLimit;
    }

    public Float getAcTypeLb() {
        return AcTypeLb;
    }

    public void setAcTypeLb(Float AcTypeLb) {
        this.AcTypeLb = AcTypeLb;
    }

    public Float getAcRegCargWeight() {
        return AcRegCargWeight;
    }

    public void setAcRegCargWeight(Float AcRegCargWeight) {
        this.AcRegCargWeight = AcRegCargWeight;
    }

    public Float getAcRegSbWeight() {
        return AcRegSbWeight;
    }

    public void setAcRegSbWeight(Float AcRegSbWeight) {
        this.AcRegSbWeight = AcRegSbWeight;
    }

    public Float getSeatLastLimit() {
        return SeatLastLimit;
    }

    public void setSeatLastLimit(Float SeatLastLimit) {
        this.SeatLastLimit = SeatLastLimit;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    public String getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(String SysVersion) {
        this.SysVersion = SysVersion;
    }

    public Float getXPos() {
        return XPos;
    }

    public void setXPos(Float XPos) {
        this.XPos = XPos;
    }

    public Float getYPos() {
        return YPos;
    }

    public void setYPos(Float YPos) {
        this.YPos = YPos;
    }

    public String getDirection() {
        return Direction;
    }

    public void setDirection(String Direction) {
        this.Direction = Direction;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public float getSeatWeight() {
        return seatWeight;
    }

    public void setSeatWeight(float seatWeight) {
        this.seatWeight = seatWeight;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
