package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SystemVersion.
 */
public class SystemVersion {

    private Long id;
    private String VserionName;
    private int vserion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SystemVersion() {
    }

    public SystemVersion(Long id) {
        this.id = id;
    }

    public SystemVersion(Long id, String VserionName, int vserion) {
        this.id = id;
        this.VserionName = VserionName;
        this.vserion = vserion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVserionName() {
        return VserionName;
    }

    public void setVserionName(String VserionName) {
        this.VserionName = VserionName;
    }

    public int getVserion() {
        return vserion;
    }

    public void setVserion(int vserion) {
        this.vserion = vserion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
