package com.xiaoqing.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table user.
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String UserName;
    private String UserCode;
    private String DepCode;
    private String UserPassWord;
    private String CodeCheck;
    private String Grant_S_M;
    private String ActiveStart;
    private int SysVersion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String UserName, String UserCode, String DepCode, String UserPassWord, String CodeCheck, String Grant_S_M, String ActiveStart, int SysVersion) {
        this.id = id;
        this.UserName = UserName;
        this.UserCode = UserCode;
        this.DepCode = DepCode;
        this.UserPassWord = UserPassWord;
        this.CodeCheck = CodeCheck;
        this.Grant_S_M = Grant_S_M;
        this.ActiveStart = ActiveStart;
        this.SysVersion = SysVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName() {
        return UserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public String getDepCode() {
        return DepCode;
    }

    public void setDepCode(String DepCode) {
        this.DepCode = DepCode;
    }

    public String getUserPassWord() {
        return UserPassWord;
    }

    public void setUserPassWord(String UserPassWord) {
        this.UserPassWord = UserPassWord;
    }

    public String getCodeCheck() {
        return CodeCheck;
    }

    public void setCodeCheck(String CodeCheck) {
        this.CodeCheck = CodeCheck;
    }

    public String getGrant_S_M() {
        return Grant_S_M;
    }

    public void setGrant_S_M(String Grant_S_M) {
        this.Grant_S_M = Grant_S_M;
    }

    public String getActiveStart() {
        return ActiveStart;
    }

    public void setActiveStart(String ActiveStart) {
        this.ActiveStart = ActiveStart;
    }

    public int getSysVersion() {
        return SysVersion;
    }

    public void setSysVersion(int SysVersion) {
        this.SysVersion = SysVersion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
