package com.uandme.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AC_WEOGHT_LIMIT.
 */
public class AcWeoghtLimit {

    private long id;
    private String AcType;
    private Integer Weight;
    private Double WeightCg1;
    private Double WeightCg2;
    private String OpUser;
    private String OpDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AcWeoghtLimit() {
    }

    public AcWeoghtLimit(long id) {
        this.id = id;
    }

    public AcWeoghtLimit(long id, String AcType, Integer Weight, Double WeightCg1, Double WeightCg2, String OpUser, String OpDate) {
        this.id = id;
        this.AcType = AcType;
        this.Weight = Weight;
        this.WeightCg1 = WeightCg1;
        this.WeightCg2 = WeightCg2;
        this.OpUser = OpUser;
        this.OpDate = OpDate;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAcType() {
        return AcType;
    }

    public void setAcType(String AcType) {
        this.AcType = AcType;
    }

    public Integer getWeight() {
        return Weight;
    }

    public void setWeight(Integer Weight) {
        this.Weight = Weight;
    }

    public Double getWeightCg1() {
        return WeightCg1;
    }

    public void setWeightCg1(Double WeightCg1) {
        this.WeightCg1 = WeightCg1;
    }

    public Double getWeightCg2() {
        return WeightCg2;
    }

    public void setWeightCg2(Double WeightCg2) {
        this.WeightCg2 = WeightCg2;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
