package com.uandme.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ADD_FLIGHT_INFO.
 */
public class AddFlightInfo implements java.io.Serializable {

    private String FlightId;
    private String FlightDate;
    private String AircraftReg;
    private String AircraftType;
    private String FlightNo;
    private String Dep4Code;
    private String DepAirportName;
    private String Arr4Code;
    private String ArrAirportName;
    private String MaxFule;
    private String RealFule;
    private String SlieFule;
    private String RouteFule;
    private String TofWeight;
    private String LandWeight;
    private String NoFuleWeight;
    private String AirportLimitWeight;
    private String BalancePic;
    private String BalancePicName;
    private String OpUser;
    private String OpDate;
    private String weightCg;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AddFlightInfo() {
    }

    public AddFlightInfo(String FlightId, String FlightDate, String AircraftReg, String AircraftType, String FlightNo, String Dep4Code, String DepAirportName, String Arr4Code, String ArrAirportName, String MaxFule, String RealFule, String SlieFule, String RouteFule, String TofWeight, String LandWeight, String NoFuleWeight, String AirportLimitWeight, String BalancePic, String BalancePicName, String OpUser, String OpDate, String weightCg) {
        this.FlightId = FlightId;
        this.FlightDate = FlightDate;
        this.AircraftReg = AircraftReg;
        this.AircraftType = AircraftType;
        this.FlightNo = FlightNo;
        this.Dep4Code = Dep4Code;
        this.DepAirportName = DepAirportName;
        this.Arr4Code = Arr4Code;
        this.ArrAirportName = ArrAirportName;
        this.MaxFule = MaxFule;
        this.RealFule = RealFule;
        this.SlieFule = SlieFule;
        this.RouteFule = RouteFule;
        this.TofWeight = TofWeight;
        this.LandWeight = LandWeight;
        this.NoFuleWeight = NoFuleWeight;
        this.AirportLimitWeight = AirportLimitWeight;
        this.BalancePic = BalancePic;
        this.BalancePicName = BalancePicName;
        this.OpUser = OpUser;
        this.OpDate = OpDate;
        this.weightCg = weightCg;
    }

    public String getFlightId() {
        return FlightId;
    }

    public void setFlightId(String FlightId) {
        this.FlightId = FlightId;
    }

    public String getFlightDate() {
        return FlightDate;
    }

    public void setFlightDate(String FlightDate) {
        this.FlightDate = FlightDate;
    }

    public String getAircraftReg() {
        return AircraftReg;
    }

    public void setAircraftReg(String AircraftReg) {
        this.AircraftReg = AircraftReg;
    }

    public String getAircraftType() {
        return AircraftType;
    }

    public void setAircraftType(String AircraftType) {
        this.AircraftType = AircraftType;
    }

    public String getFlightNo() {
        return FlightNo;
    }

    public void setFlightNo(String FlightNo) {
        this.FlightNo = FlightNo;
    }

    public String getDep4Code() {
        return Dep4Code;
    }

    public void setDep4Code(String Dep4Code) {
        this.Dep4Code = Dep4Code;
    }

    public String getDepAirportName() {
        return DepAirportName;
    }

    public void setDepAirportName(String DepAirportName) {
        this.DepAirportName = DepAirportName;
    }

    public String getArr4Code() {
        return Arr4Code;
    }

    public void setArr4Code(String Arr4Code) {
        this.Arr4Code = Arr4Code;
    }

    public String getArrAirportName() {
        return ArrAirportName;
    }

    public void setArrAirportName(String ArrAirportName) {
        this.ArrAirportName = ArrAirportName;
    }

    public String getMaxFule() {
        return MaxFule;
    }

    public void setMaxFule(String MaxFule) {
        this.MaxFule = MaxFule;
    }

    public String getRealFule() {
        return RealFule;
    }

    public void setRealFule(String RealFule) {
        this.RealFule = RealFule;
    }

    public String getSlieFule() {
        return SlieFule;
    }

    public void setSlieFule(String SlieFule) {
        this.SlieFule = SlieFule;
    }

    public String getRouteFule() {
        return RouteFule;
    }

    public void setRouteFule(String RouteFule) {
        this.RouteFule = RouteFule;
    }

    public String getTofWeight() {
        return TofWeight;
    }

    public void setTofWeight(String TofWeight) {
        this.TofWeight = TofWeight;
    }

    public String getLandWeight() {
        return LandWeight;
    }

    public void setLandWeight(String LandWeight) {
        this.LandWeight = LandWeight;
    }

    public String getNoFuleWeight() {
        return NoFuleWeight;
    }

    public void setNoFuleWeight(String NoFuleWeight) {
        this.NoFuleWeight = NoFuleWeight;
    }

    public String getAirportLimitWeight() {
        return AirportLimitWeight;
    }

    public void setAirportLimitWeight(String AirportLimitWeight) {
        this.AirportLimitWeight = AirportLimitWeight;
    }

    public String getBalancePic() {
        return BalancePic;
    }

    public void setBalancePic(String BalancePic) {
        this.BalancePic = BalancePic;
    }

    public String getBalancePicName() {
        return BalancePicName;
    }

    public void setBalancePicName(String BalancePicName) {
        this.BalancePicName = BalancePicName;
    }

    public String getOpUser() {
        return OpUser;
    }

    public void setOpUser(String OpUser) {
        this.OpUser = OpUser;
    }

    public String getOpDate() {
        return OpDate;
    }

    public void setOpDate(String OpDate) {
        this.OpDate = OpDate;
    }

    public String getWeightCg() {
        return weightCg;
    }

    public void setWeightCg(String weightCg) {
        this.weightCg = weightCg;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
