package com.uandme.flight.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table user.
 */
public class User {

    private long id;
    private String uuid;
    private String email;
    private String role;
    private String created_at;
    private String updated_at;
    private String first_name;
    private String last_name;
    private String handicap_style;
    private String handicap_style_1;
    private String handicap_style_2;
    private double height;
    private double weight;
    private int birth_year;
    private int gender;
    private int right_handed;
    private String grip_posture;
    private String grip_position;
    private String is_phone_timer;
    private String video_record;
    private String auto_save;
    private String auto_comment;
    private String sound_effect;
    private String text_hint;
    private String power_save;
    private String unit;
    private String impact_detect;
    private String goals;
    private String user_image_file_name;
    private String user_image_content_type;
    private String user_image_file_size;
    private String user_image_fingerprint;
    private String versions;
    private String language;
    private String timezone;
    private String test_account;
    private String user_role;
    private String flags;
    private String authentication_token;
    private String profile;
    private String avatar_url;
    private boolean facebook_connected;
    private boolean wechat_connected;
    private int position;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(long id) {
        this.id = id;
    }

    public User(long id, String uuid, String email, String role, String created_at, String updated_at, String first_name, String last_name, String handicap_style, String handicap_style_1, String handicap_style_2, double height, double weight, int birth_year, int gender, int right_handed, String grip_posture, String grip_position, String is_phone_timer, String video_record, String auto_save, String auto_comment, String sound_effect, String text_hint, String power_save, String unit, String impact_detect, String goals, String user_image_file_name, String user_image_content_type, String user_image_file_size, String user_image_fingerprint, String versions, String language, String timezone, String test_account, String user_role, String flags, String authentication_token, String profile, String avatar_url, boolean facebook_connected, boolean wechat_connected, int position) {
        this.id = id;
        this.uuid = uuid;
        this.email = email;
        this.role = role;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.first_name = first_name;
        this.last_name = last_name;
        this.handicap_style = handicap_style;
        this.handicap_style_1 = handicap_style_1;
        this.handicap_style_2 = handicap_style_2;
        this.height = height;
        this.weight = weight;
        this.birth_year = birth_year;
        this.gender = gender;
        this.right_handed = right_handed;
        this.grip_posture = grip_posture;
        this.grip_position = grip_position;
        this.is_phone_timer = is_phone_timer;
        this.video_record = video_record;
        this.auto_save = auto_save;
        this.auto_comment = auto_comment;
        this.sound_effect = sound_effect;
        this.text_hint = text_hint;
        this.power_save = power_save;
        this.unit = unit;
        this.impact_detect = impact_detect;
        this.goals = goals;
        this.user_image_file_name = user_image_file_name;
        this.user_image_content_type = user_image_content_type;
        this.user_image_file_size = user_image_file_size;
        this.user_image_fingerprint = user_image_fingerprint;
        this.versions = versions;
        this.language = language;
        this.timezone = timezone;
        this.test_account = test_account;
        this.user_role = user_role;
        this.flags = flags;
        this.authentication_token = authentication_token;
        this.profile = profile;
        this.avatar_url = avatar_url;
        this.facebook_connected = facebook_connected;
        this.wechat_connected = wechat_connected;
        this.position = position;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getHandicap_style() {
        return handicap_style;
    }

    public void setHandicap_style(String handicap_style) {
        this.handicap_style = handicap_style;
    }

    public String getHandicap_style_1() {
        return handicap_style_1;
    }

    public void setHandicap_style_1(String handicap_style_1) {
        this.handicap_style_1 = handicap_style_1;
    }

    public String getHandicap_style_2() {
        return handicap_style_2;
    }

    public void setHandicap_style_2(String handicap_style_2) {
        this.handicap_style_2 = handicap_style_2;
    }

    public double getHeight() {
        return height;
    }

    public void setHeight(double height) {
        this.height = height;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getBirth_year() {
        return birth_year;
    }

    public void setBirth_year(int birth_year) {
        this.birth_year = birth_year;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public int getRight_handed() {
        return right_handed;
    }

    public void setRight_handed(int right_handed) {
        this.right_handed = right_handed;
    }

    public String getGrip_posture() {
        return grip_posture;
    }

    public void setGrip_posture(String grip_posture) {
        this.grip_posture = grip_posture;
    }

    public String getGrip_position() {
        return grip_position;
    }

    public void setGrip_position(String grip_position) {
        this.grip_position = grip_position;
    }

    public String getIs_phone_timer() {
        return is_phone_timer;
    }

    public void setIs_phone_timer(String is_phone_timer) {
        this.is_phone_timer = is_phone_timer;
    }

    public String getVideo_record() {
        return video_record;
    }

    public void setVideo_record(String video_record) {
        this.video_record = video_record;
    }

    public String getAuto_save() {
        return auto_save;
    }

    public void setAuto_save(String auto_save) {
        this.auto_save = auto_save;
    }

    public String getAuto_comment() {
        return auto_comment;
    }

    public void setAuto_comment(String auto_comment) {
        this.auto_comment = auto_comment;
    }

    public String getSound_effect() {
        return sound_effect;
    }

    public void setSound_effect(String sound_effect) {
        this.sound_effect = sound_effect;
    }

    public String getText_hint() {
        return text_hint;
    }

    public void setText_hint(String text_hint) {
        this.text_hint = text_hint;
    }

    public String getPower_save() {
        return power_save;
    }

    public void setPower_save(String power_save) {
        this.power_save = power_save;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getImpact_detect() {
        return impact_detect;
    }

    public void setImpact_detect(String impact_detect) {
        this.impact_detect = impact_detect;
    }

    public String getGoals() {
        return goals;
    }

    public void setGoals(String goals) {
        this.goals = goals;
    }

    public String getUser_image_file_name() {
        return user_image_file_name;
    }

    public void setUser_image_file_name(String user_image_file_name) {
        this.user_image_file_name = user_image_file_name;
    }

    public String getUser_image_content_type() {
        return user_image_content_type;
    }

    public void setUser_image_content_type(String user_image_content_type) {
        this.user_image_content_type = user_image_content_type;
    }

    public String getUser_image_file_size() {
        return user_image_file_size;
    }

    public void setUser_image_file_size(String user_image_file_size) {
        this.user_image_file_size = user_image_file_size;
    }

    public String getUser_image_fingerprint() {
        return user_image_fingerprint;
    }

    public void setUser_image_fingerprint(String user_image_fingerprint) {
        this.user_image_fingerprint = user_image_fingerprint;
    }

    public String getVersions() {
        return versions;
    }

    public void setVersions(String versions) {
        this.versions = versions;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public String getTest_account() {
        return test_account;
    }

    public void setTest_account(String test_account) {
        this.test_account = test_account;
    }

    public String getUser_role() {
        return user_role;
    }

    public void setUser_role(String user_role) {
        this.user_role = user_role;
    }

    public String getFlags() {
        return flags;
    }

    public void setFlags(String flags) {
        this.flags = flags;
    }

    public String getAuthentication_token() {
        return authentication_token;
    }

    public void setAuthentication_token(String authentication_token) {
        this.authentication_token = authentication_token;
    }

    public String getProfile() {
        return profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public String getAvatar_url() {
        return avatar_url;
    }

    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url;
    }

    public boolean getFacebook_connected() {
        return facebook_connected;
    }

    public void setFacebook_connected(boolean facebook_connected) {
        this.facebook_connected = facebook_connected;
    }

    public boolean getWechat_connected() {
        return wechat_connected;
    }

    public void setWechat_connected(boolean wechat_connected) {
        this.wechat_connected = wechat_connected;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
